import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/navbar/Navbar';
import { UserProvider } from './UserContext';

export const metadata: Metadata = {
  title: 'CRUD Application with Next.js and Firebase',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <UserProvider>
          <Navbar />
          {children}
        </UserProvider>
      </body>
    </html>
  )
}
